spring:
  application:
    name: ootd
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  profiles:
    active:
      - dev
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: ootdboo1@gmail.com
    password: ${GOOGLE_APP_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,caches
  endpoint:
    health:
      show-details: always
  observations:
    annotations:
      enabled: true

kakao:
  api:
    key: ${KAKAO_API_KEY}

weather:
  api:
    key: ${WEATHER_API_KEY}
  batch:
    thread-pool-size: 10  # 동시 실행 스레드 수
    chunk-size: 10        # 청크 크기
    regions-per-partition: 5  # 파티션당 지역 수
  regions:
    file:
      path: classpath:regions.csv

info:
  name: ootd
  version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.5.3
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${ootd.storage.type}
      path: ${ootd.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.maxFileSize}
      max-request-size: ${spring.servlet.multipart.maxRequestSize}

ootd:
  storage:
    type: s3
    s3:
      access-key: ${AWS_S3_ACCESS_KEY} # local -> .env, prod -> github secret
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}

logging:
  level:
    root: info
app:
  jwt:
    secret: "F811B1184C98D8543B1351D93948481900aDYQ82347641"
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

