server:
  port: 80

spring:
  application:
    name: ootd
  datasource:
    url: ${DATASOURCE_URL}
    username: <PROD_DB_USERNAME>
    password: <PROD_DB_PASSWORD>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

info:
  name: ootd
  version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.5.3
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}

ootd:
  storage:
    type: s3
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}   # GitHub Secrets로 설정
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}

logging:
  level:
    root: debug